info :
  build:
    artifact : @project.artifactId@
    name : @project.name@
    description : @project.description@
    version : @project.version@
spring:
  profiles:
    active: dev
  application:
    name: @project.description@

logging:
  name: shorturl
  level: debug
  path: /tmp/logs/

---
#dev 环境
spring:
  profiles: dev
  datasource:
      url: jdbc:postgresql://192.168.1.2:5432/ms
      username: ms
      password: spiderdt
      driver-class-name: org.postgresql.Driver
  boot:
    admin:
      url: http://192.168.1.5:9088
  redis:
    host: 192.168.1.2
    port: 6380
    database: 0
    timeout: 3000
    prefix: url
    password: spiderdt
shorturl:
  incrkey: surl_index
  http_prefix: 127.0.0.1:8905/s/

server:
  tomcat:
    max-threads: 100
    min-spare-threads: 20
  port: 8906
  connection-timeout: 5000
---
#test 环境
spring:
  profiles: test
  datasource:
      url: jdbc:postgresql://192.168.1.5:5432/ms
      username: ms
      password: spiderdt
      driver-class-name: org.postgresql.Driver
  redis:
    host: 127.0.0.1
    port: 6380
    database: 0
    timeout: 3000
    prefix: url
    password: spiderdt
  boot:
    admin:
      url: http://192.168.1.5:9088
server:
  tomcat:
    max-threads: 100
    min-spare-threads: 20
  port: 8906
  connection-timeout: 5000
spiderdt:
  rate: test



---
#prod 环境
spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/ms
    username: ms
    password: spiderdt
    driver-class-name: org.postgresql.Driver
  redis:
    host: 127.0.0.1
    port: 6380
    database: 0
    timeout: 3000
    prefix: url
    password: spiderdt
  boot:
    admin:
      url: http://192.168.1.5:9088

server:
  tomcat:
    max-threads: 100
    min-spare-threads: 20
  port: 8906
  connection-timeout: 5000

---
#aws 环境
spring:
  profiles: aws
  datasource:
    url: jdbc:postgresql://172.31.5.139:6543/ms
    username: ms
    password: spiderdt
    driver-class-name: org.postgresql.Driver
  redis:
    host: 172.31.5.139
    port: 6380
    database: 0
    timeout: 3000
    prefix: url
    password: spiderdt
  boot:
    admin:
      url: http://172.31.5.139:9088
server:
  tomcat:
    max-threads: 100
    min-spare-threads: 20
  port: 8906
  connection-timeout: 5000

shorturl:
  incrkey: surl_index
  http_prefix: spiderdt.cn/

logging:
  level: info
  path: /data/tomcat/logs/

---
#pub config
mybatis:
  mapper-locations: classpath:mapper/*Dao.xml
  config-location: classpath:mybatis/mybatis-config.xml
  executor-type: simple
  type-aliases-package: com.spiderdt.common.entity

#系统自带默认的tomcat,也可以使用jetty。需要配置jetty依赖。
management:
  security:
    enabled: false

spiderdt:
  task-thread-nums: 32

